Drop TABLE IF EXISTS users;

Create TABLE users(
userId BIGINT NOT NULL AUTO_INCREMENT,
userName VARCHAR(20) NOT NULL UNIQUE,
userPsd VARCHAR(200) NOT NULL,
regTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(userId)
)engine=INNODB AUTO_INCREMENT=10001 DEFAULT CHARSET=GBK