DROP TABLE IF EXISTS blog;

CREATE TABLE blog(
tid BIGINT AUTO_INCREMENT PRIMARY KEY,
userId BIGINT NOT NULL,
title VARCHAR(500) NOT NULL,
author VARCHAR(20),
type INT,
loadURL VARCHAR(500),
label VARCHAR(300),
decoration VARCHAR(500),
content TEXT,
createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
state INT,
FOREIGN KEY(userId) REFERENCES users(userId)
)engine=INNODB AUTO_INCREMENT=10001 DEFAULT CHARSET=GBK;