DROP TABLE IF EXISTS response2;

CREATE TABLE response2 (
	postId2 BIGINT AUTO_INCREMENT PRIMARY KEY,
	postId BIGINT NOT NULL,
	userId BIGINT NOT NULL,
	content VARCHAR (500) NOT NULL,
	createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_response2_users FOREIGN KEY(userId) REFERENCES users(userId),
	CONSTRAINT FK_response2_response FOREIGN KEY(postId) REFERENCES response(postId)
) ENGINE = INNODB AUTO_INCREMENT = 10001 DEFAULT CHARSET = GBK;